[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules","lib"]
test = "contracts/tests"
cache_path = "forge-cache"
solc = "0.8.25"
evm_version ="shanghai"
optimizer = true
optimizer_runs = 999999
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
base = "${BASE_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_MAINNET_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
